version: "2"
services:
  jenkins:
    user: root
    # We run as root locally to avoid access denied errors on the volume mounts,
    # production uses 'jenkins' user
    ports:
      - 80:8080
    build:
      # Build an image from the Dockerfile in the current directory
      context: .
      dockerfile: images/Dockerfile
    restart: always
    env_file: .env
    # volumes:
    #   - "/var/run/docker.sock:/var/run/docker.sock"
    #   - "jenkins_home:/var/jenkins_home/"

# volumes:
#   jenkins_home: