jenkins:
  systemMessage: "Jenkins Server Configuration\n\n"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "Administrators"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - ${ADMIN_USER}
          - name: "BasicAccess"
            description: "Minimal permissions to access jenkins"
            permissions:
              - "Overall/Read"
              - "Agent/Build"
              - "Job/Build"
              - "Job/Read"
              - "Run/Replay"
              - "View/Read"
            assignments:
              - ${LOCAL}
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}
        - id: ${LOCAL}
          password: ${LOCAL_PASSWORD}

jobs:
  - script: >
      freeStyleJob('seed-job') {
        
        if( !System.getenv('DOCKER_COMPOSE') ) {
          scm {
            git {
              remote {
                url('https://github.com/ricardocutzhernandez/jenkins-server.git')
              }
              branches('master')
            }
          }
        }
        displayName('seed-job')
        steps {
          dsl {
            external('jobs/**')
            removeAction('DELETE')
            removeViewAction('DELETE')
          }
        }
        publishers {
          downstreamParameterized {
            trigger('General/seed_sharedlib') {
              condition('SUCCESS')
            }
          }
        }
      }
